# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 648)
        MainWindow.setMinimumSize(QtCore.QSize(858, 648))
        MainWindow.setMaximumSize(QtCore.QSize(858, 648))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboAlgoritmo = QtWidgets.QComboBox(self.centralwidget)
        self.comboAlgoritmo.setGeometry(QtCore.QRect(60, 130, 171, 31))
        self.comboAlgoritmo.setObjectName("comboAlgoritmo")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.comboAlgoritmo.addItem("")
        self.labelTitulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTitulo.setGeometry(QtCore.QRect(90, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setFrameShape(QtWidgets.QFrame.Box)
        self.labelTitulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelAlgoritmo = QtWidgets.QLabel(self.centralwidget)
        self.labelAlgoritmo.setGeometry(QtCore.QRect(60, 90, 181, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.labelAlgoritmo.setFont(font)
        self.labelAlgoritmo.setObjectName("labelAlgoritmo")
        self.fieldNombre = QtWidgets.QLineEdit(self.centralwidget)
        self.fieldNombre.setGeometry(QtCore.QRect(470, 90, 121, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fieldNombre.setFont(font)
        self.fieldNombre.setObjectName("fieldNombre")
        self.labelDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelDatos.setGeometry(QtCore.QRect(600, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.labelDatos.setFont(font)
        self.labelDatos.setFrameShape(QtWidgets.QFrame.Box)
        self.labelDatos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelDatos.setObjectName("labelDatos")
        self.labelNombre = QtWidgets.QLabel(self.centralwidget)
        self.labelNombre.setGeometry(QtCore.QRect(510, 60, 54, 17))
        self.labelNombre.setObjectName("labelNombre")
        self.fieldRafaga = QtWidgets.QLineEdit(self.centralwidget)
        self.fieldRafaga.setGeometry(QtCore.QRect(610, 90, 113, 29))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.fieldRafaga.setFont(font)
        self.fieldRafaga.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.fieldRafaga.setObjectName("fieldRafaga")
        self.labelRafaga = QtWidgets.QLabel(self.centralwidget)
        self.labelRafaga.setGeometry(QtCore.QRect(640, 60, 54, 17))
        self.labelRafaga.setObjectName("labelRafaga")
        self.TablaEstado = QtWidgets.QTableWidget(self.centralwidget)
        self.TablaEstado.setGeometry(QtCore.QRect(20, 260, 521, 192))
        self.TablaEstado.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.TablaEstado.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TablaEstado.setColumnCount(5)
        self.TablaEstado.setObjectName("TablaEstado")
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstado.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaEstado.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.TablaEstado.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(4, item)
        
        self.btnAgregar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(460, 190, 87, 29))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Iconos/agregar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar.setIcon(icon)
        self.btnAgregar.setObjectName("btnAgregar")
        self.btnBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBorrar.setGeometry(QtCore.QRect(560, 190, 121, 29))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Iconos/borrar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBorrar.setIcon(icon1)
        self.btnBorrar.setObjectName("btnBorrar")
        self.btnIniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnIniciar.setGeometry(QtCore.QRect(50, 190, 87, 29))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Iconos/Reproducir.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIniciar.setIcon(icon2)
        self.btnIniciar.setObjectName("btnIniciar")
        self.btnReiniciar = QtWidgets.QPushButton(self.centralwidget)
        self.btnReiniciar.setGeometry(QtCore.QRect(720, 360, 87, 29))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Iconos/reiniciar.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReiniciar.setIcon(icon3)
        self.btnReiniciar.setCheckable(False)
        self.btnReiniciar.setObjectName("btnReiniciar")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 871, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(420, 0, 20, 241))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btnEliminar = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(580, 260, 87, 29))
        self.btnEliminar.setAutoFillBackground(False)
        self.btnEliminar.setObjectName("btnEliminar")
        self.frameTiempo = QtWidgets.QFrame(self.centralwidget)
        self.frameTiempo.setGeometry(QtCore.QRect(700, 260, 131, 91))
        self.frameTiempo.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frameTiempo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTiempo.setObjectName("frameTiempo")
        self.lcdTotal = QtWidgets.QLCDNumber(self.frameTiempo)
        self.lcdTotal.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.lcdTotal.setObjectName("lcdTotal")
        self.labelTIempototal = QtWidgets.QLabel(self.frameTiempo)
        self.labelTIempototal.setGeometry(QtCore.QRect(20, 10, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.labelTIempototal.setFont(font)
        self.labelTIempototal.setObjectName("labelTiempototal")
        self.btnRandom = QtWidgets.QPushButton(self.centralwidget)
        self.btnRandom.setGeometry(QtCore.QRect(690, 190, 131, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Iconos/random.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRandom.setIcon(icon4)
        self.btnRandom.setObjectName("btnRandom")
        self.btnDetener = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetener.setGeometry(QtCore.QRect(150, 190, 87, 29))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Iconos/detener.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetener.setIcon(icon5)
        self.btnDetener.setCheckable(False)
        self.btnDetener.setObjectName("btnDetener")
        self.btnEliminartodo = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminartodo.setGeometry(QtCore.QRect(580, 300, 87, 29))
        self.btnEliminartodo.setObjectName("btnEliminartodo")
        self.frameMemoria = QtWidgets.QFrame(self.centralwidget)
        self.frameMemoria.setGeometry(QtCore.QRect(270, 70, 141, 80))
        self.frameMemoria.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameMemoria.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMemoria.setObjectName("frameMemoria")
        self.labelMemoria = QtWidgets.QLabel(self.frameMemoria)
        self.labelMemoria.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.labelMemoria.setObjectName("labelMemoria")
        self.fieldMemoria = QtWidgets.QLineEdit(self.frameMemoria)
        self.fieldMemoria.setGeometry(QtCore.QRect(10, 40, 91, 29))
        self.fieldMemoria.setObjectName("fieldMemoria")
        self.lockMemoria = QtWidgets.QPushButton(self.frameMemoria)
        self.lockMemoria.setGeometry(QtCore.QRect(110, 40, 21, 29))
        self.lockMemoria.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Iconos/cerrado.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lockMemoria.setIcon(icon6)
        self.lockMemoria.setCheckable(True)
        self.lockMemoria.setChecked(False)
        self.lockMemoria.setObjectName("lockMemoria")
        self.frameQuantum = QtWidgets.QFrame(self.centralwidget)
        self.frameQuantum.setGeometry(QtCore.QRect(280, 150, 121, 71))
        self.frameQuantum.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameQuantum.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameQuantum.setObjectName("frameQuantum")
        self.btnEstablecerQuantum = QtWidgets.QPushButton(self.frameQuantum)
        self.btnEstablecerQuantum.setGeometry(QtCore.QRect(50, 40, 71, 29))
        self.btnEstablecerQuantum.setObjectName("btnEstablecerQuantum")
        self.fieldQuantum = QtWidgets.QLineEdit(self.frameQuantum)
        self.fieldQuantum.setGeometry(QtCore.QRect(10, 40, 31, 29))
        font = QtGui.QFont()
        font.setFamily("Impact")
        self.fieldQuantum.setFont(font)
        self.fieldQuantum.setObjectName("fieldQuantum")
        self.labelQuantum = QtWidgets.QLabel(self.frameQuantum)
        self.labelQuantum.setGeometry(QtCore.QRect(30, 10, 61, 17))
        self.labelQuantum.setObjectName("labelQuantum")
        self.fieldMemoriaP = QtWidgets.QLineEdit(self.centralwidget)
        self.fieldMemoriaP.setGeometry(QtCore.QRect(600, 140, 113, 29))
        self.fieldMemoriaP.setObjectName("fieldMemoriaP")
        self.labelMemoria_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelMemoria_2.setGeometry(QtCore.QRect(530, 140, 61, 20))
        self.labelMemoria_2.setObjectName("labelMemoria_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(730, 50, 120, 80))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelPrioridadl = QtWidgets.QLabel(self.frame)
        self.labelPrioridadl.setGeometry(QtCore.QRect(30, 10, 61, 17))
        self.labelPrioridadl.setObjectName("labelPrioridadl")
        self.fieldPrioridad = QtWidgets.QLineEdit(self.frame)
        self.fieldPrioridad.setGeometry(QtCore.QRect(30, 40, 51, 29))
        self.fieldPrioridad.setObjectName("fieldPrioridad")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

          ## Validadores
        self.fieldMemoria.setValidator(QtGui.QIntValidator())
        self.fieldMemoriaP.setValidator(QtGui.QIntValidator())
        self.fieldPrioridad.setValidator(QtGui.QIntValidator())
        self.fieldQuantum.setValidator(QtGui.QIntValidator())
        self.fieldRafaga.setValidator(QtGui.QIntValidator()) 
        ##---

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de procesos"))
        self.comboAlgoritmo.setItemText(0, _translate("MainWindow", "Round-Robin"))
        self.comboAlgoritmo.setItemText(1, _translate("MainWindow", "Shortest Job First"))
        self.comboAlgoritmo.setItemText(2, _translate("MainWindow", "First-Come First-Served"))
        self.comboAlgoritmo.setItemText(3, _translate("MainWindow", "Priority Scheduling"))
        self.labelTitulo.setText(_translate("MainWindow", "Simulador de Procesos"))
        self.labelAlgoritmo.setText(_translate("MainWindow", "Algoritmo de Planificacion"))
        self.labelDatos.setText(_translate("MainWindow", "Datos del proceso"))
        self.labelNombre.setText(_translate("MainWindow", "Nombre"))
        self.labelRafaga.setText(_translate("MainWindow", "Rafaga"))
        item = self.TablaEstado.verticalHeaderItem(0)
        item = self.TablaEstado.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre"))
        item = self.TablaEstado.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rafaga"))
        item = self.TablaEstado.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Memoria"))
        item = self.TablaEstado.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estado"))
        item = self.TablaEstado.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Porcentaje %"))
        __sortingEnabled = self.TablaEstado.isSortingEnabled()
        self.TablaEstado.setSortingEnabled(False)
        self.TablaEstado.setSortingEnabled(__sortingEnabled)
        self.btnAgregar.setText(_translate("MainWindow", "Agregar"))
        self.btnBorrar.setText(_translate("MainWindow", "Borrar Campos"))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar"))
        self.btnReiniciar.setText(_translate("MainWindow", "Reiniciar"))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar"))
        self.labelTIempototal.setText(_translate("MainWindow", "Tiempo Total"))
        self.btnRandom.setText(_translate("MainWindow", "Proceso Random"))
        self.btnDetener.setText(_translate("MainWindow", "Detener"))
        self.btnEliminartodo.setText(_translate("MainWindow", "Eliminar Todo"))
        self.labelMemoria.setText(_translate("MainWindow", "Memoria Total"))
        self.btnEstablecerQuantum.setText(_translate("MainWindow", "Establecer"))
        self.labelQuantum.setText(_translate("MainWindow", "Quantum"))
        self.labelMemoria_2.setText(_translate("MainWindow", "Memoria"))
        self.labelPrioridadl.setText(_translate("MainWindow", "Prioridad"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

