# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(858, 648)
        MainWindow.setMinimumSize(QtCore.QSize(858, 648))
        MainWindow.setMaximumSize(QtCore.QSize(858, 648))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.comboAlgoritmo = QtGui.QComboBox(self.centralwidget)
        self.comboAlgoritmo.setGeometry(QtCore.QRect(60, 130, 171, 31))
        self.comboAlgoritmo.setObjectName(_fromUtf8("comboAlgoritmo"))
        self.comboAlgoritmo.addItem(_fromUtf8(""))
        self.comboAlgoritmo.addItem(_fromUtf8(""))
        self.comboAlgoritmo.addItem(_fromUtf8(""))
        self.comboAlgoritmo.addItem(_fromUtf8(""))
        self.labelTitulo = QtGui.QLabel(self.centralwidget)
        self.labelTitulo.setGeometry(QtCore.QRect(90, 10, 251, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setFrameShape(QtGui.QFrame.Box)
        self.labelTitulo.setFrameShadow(QtGui.QFrame.Raised)
        self.labelTitulo.setObjectName(_fromUtf8("labelTitulo"))
        self.labelAlgoritmo = QtGui.QLabel(self.centralwidget)
        self.labelAlgoritmo.setGeometry(QtCore.QRect(60, 90, 181, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.labelAlgoritmo.setFont(font)
        self.labelAlgoritmo.setObjectName(_fromUtf8("labelAlgoritmo"))
        self.fieldNombre = QtGui.QLineEdit(self.centralwidget)
        self.fieldNombre.setGeometry(QtCore.QRect(470, 90, 121, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fieldNombre.setFont(font)
        self.fieldNombre.setObjectName(_fromUtf8("fieldNombre"))
        self.labelDatos = QtGui.QLabel(self.centralwidget)
        self.labelDatos.setGeometry(QtCore.QRect(600, 10, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.labelDatos.setFont(font)
        self.labelDatos.setFrameShape(QtGui.QFrame.Box)
        self.labelDatos.setFrameShadow(QtGui.QFrame.Raised)
        self.labelDatos.setObjectName(_fromUtf8("labelDatos"))
        self.labelNombre = QtGui.QLabel(self.centralwidget)
        self.labelNombre.setGeometry(QtCore.QRect(510, 60, 54, 17))
        self.labelNombre.setObjectName(_fromUtf8("labelNombre"))
        self.fieldRafaga = QtGui.QLineEdit(self.centralwidget)
        self.fieldRafaga.setGeometry(QtCore.QRect(610, 90, 113, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fieldRafaga.setFont(font)
        self.fieldRafaga.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.fieldRafaga.setObjectName(_fromUtf8("fieldRafaga"))
        self.labelRafaga = QtGui.QLabel(self.centralwidget)
        self.labelRafaga.setGeometry(QtCore.QRect(640, 60, 54, 17))
        self.labelRafaga.setObjectName(_fromUtf8("labelRafaga"))
        self.TablaEstado = QtGui.QTableWidget(self.centralwidget)
        self.TablaEstado.setGeometry(QtCore.QRect(30, 270, 521, 192))
        self.TablaEstado.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.TablaEstado.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.TablaEstado.setColumnCount(5)
        self.TablaEstado.setObjectName(_fromUtf8("TablaEstado"))
        self.TablaEstado.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.TablaEstado.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.TablaEstado.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.TablaEstado.setHorizontalHeaderItem(4, item)
        self.btnAgregar = QtGui.QPushButton(self.centralwidget)
        self.btnAgregar.setGeometry(QtCore.QRect(460, 190, 87, 29))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/agregar.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAgregar.setIcon(icon)
        self.btnAgregar.setObjectName(_fromUtf8("btnAgregar"))
        self.btnBorrar = QtGui.QPushButton(self.centralwidget)
        self.btnBorrar.setGeometry(QtCore.QRect(560, 190, 121, 29))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/borrar.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBorrar.setIcon(icon1)
        self.btnBorrar.setObjectName(_fromUtf8("btnBorrar"))
        self.btnIniciar = QtGui.QPushButton(self.centralwidget)
        self.btnIniciar.setGeometry(QtCore.QRect(50, 190, 87, 29))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/Reproducir.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnIniciar.setIcon(icon2)
        self.btnIniciar.setObjectName(_fromUtf8("btnIniciar"))
        self.btnReiniciar = QtGui.QPushButton(self.centralwidget)
        self.btnReiniciar.setGeometry(QtCore.QRect(720, 360, 87, 29))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/reiniciar.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReiniciar.setIcon(icon3)
        self.btnReiniciar.setCheckable(False)
        self.btnReiniciar.setObjectName(_fromUtf8("btnReiniciar"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 230, 871, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(420, 0, 20, 241))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.btnEliminar = QtGui.QPushButton(self.centralwidget)
        self.btnEliminar.setGeometry(QtCore.QRect(580, 260, 87, 29))
        self.btnEliminar.setAutoFillBackground(False)
        self.btnEliminar.setObjectName(_fromUtf8("btnEliminar"))
        self.frameTiempo = QtGui.QFrame(self.centralwidget)
        self.frameTiempo.setGeometry(QtCore.QRect(700, 260, 131, 91))
        self.frameTiempo.setFrameShape(QtGui.QFrame.WinPanel)
        self.frameTiempo.setFrameShadow(QtGui.QFrame.Plain)
        self.frameTiempo.setObjectName(_fromUtf8("frameTiempo"))
        self.lcdTotal = QtGui.QLCDNumber(self.frameTiempo)
        self.lcdTotal.setGeometry(QtCore.QRect(20, 40, 91, 31))
        self.lcdTotal.setObjectName(_fromUtf8("lcdTotal"))
        self.labelTIempototal = QtGui.QLabel(self.frameTiempo)
        self.labelTIempototal.setGeometry(QtCore.QRect(20, 10, 91, 17))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(11)
        self.labelTIempototal.setFont(font)
        self.labelTIempototal.setObjectName(_fromUtf8("labelTIempototal"))
        self.btnRandom = QtGui.QPushButton(self.centralwidget)
        self.btnRandom.setGeometry(QtCore.QRect(690, 190, 131, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/random.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRandom.setIcon(icon4)
        self.btnRandom.setObjectName(_fromUtf8("btnRandom"))
        self.btnDetener = QtGui.QPushButton(self.centralwidget)
        self.btnDetener.setGeometry(QtCore.QRect(150, 190, 87, 29))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/detener.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDetener.setIcon(icon5)
        self.btnDetener.setCheckable(False)
        self.btnDetener.setObjectName(_fromUtf8("btnDetener"))
        self.btnEliminartodo = QtGui.QPushButton(self.centralwidget)
        self.btnEliminartodo.setGeometry(QtCore.QRect(580, 300, 87, 29))
        self.btnEliminartodo.setObjectName(_fromUtf8("btnEliminartodo"))
        self.frameMemoria = QtGui.QFrame(self.centralwidget)
        self.frameMemoria.setGeometry(QtCore.QRect(270, 70, 141, 80))
        self.frameMemoria.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameMemoria.setFrameShadow(QtGui.QFrame.Plain)
        self.frameMemoria.setObjectName(_fromUtf8("frameMemoria"))
        self.labelMemoria = QtGui.QLabel(self.frameMemoria)
        self.labelMemoria.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.labelMemoria.setObjectName(_fromUtf8("labelMemoria"))
        self.fieldMemoria = QtGui.QLineEdit(self.frameMemoria)
        self.fieldMemoria.setGeometry(QtCore.QRect(10, 40, 91, 29))
        self.fieldMemoria.setObjectName(_fromUtf8("fieldMemoria"))
        self.lockMemoria = QtGui.QPushButton(self.frameMemoria)
        self.lockMemoria.setGeometry(QtCore.QRect(110, 40, 21, 29))
        self.lockMemoria.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Iconos/cerrado.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lockMemoria.setIcon(icon6)
        self.lockMemoria.setCheckable(True)
        self.lockMemoria.setChecked(False)
        self.lockMemoria.setObjectName(_fromUtf8("lockMemoria"))
        self.frameQuantum = QtGui.QFrame(self.centralwidget)
        self.frameQuantum.setGeometry(QtCore.QRect(280, 150, 121, 71))
        self.frameQuantum.setFrameShape(QtGui.QFrame.NoFrame)
        self.frameQuantum.setFrameShadow(QtGui.QFrame.Raised)
        self.frameQuantum.setObjectName(_fromUtf8("frameQuantum"))
        self.btnEstablecerQuantum = QtGui.QPushButton(self.frameQuantum)
        self.btnEstablecerQuantum.setGeometry(QtCore.QRect(50, 40, 71, 29))
        self.btnEstablecerQuantum.setObjectName(_fromUtf8("btnEstablecerQuantum"))
        self.fieldQuantum = QtGui.QLineEdit(self.frameQuantum)
        self.fieldQuantum.setGeometry(QtCore.QRect(10, 40, 31, 29))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fieldQuantum.setFont(font)
        self.fieldQuantum.setObjectName(_fromUtf8("fieldQuantum"))
        self.labelQuantum = QtGui.QLabel(self.frameQuantum)
        self.labelQuantum.setGeometry(QtCore.QRect(30, 10, 61, 17))
        self.labelQuantum.setObjectName(_fromUtf8("labelQuantum"))
        self.fieldMemoriaP = QtGui.QLineEdit(self.centralwidget)
        self.fieldMemoriaP.setGeometry(QtCore.QRect(600, 140, 113, 29))
        self.fieldMemoriaP.setObjectName(_fromUtf8("fieldMemoriaP"))
        self.labelMemoria_2 = QtGui.QLabel(self.centralwidget)
        self.labelMemoria_2.setGeometry(QtCore.QRect(530, 140, 61, 20))
        self.labelMemoria_2.setObjectName(_fromUtf8("labelMemoria_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(730, 50, 120, 80))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.labelPrioridadl = QtGui.QLabel(self.frame)
        self.labelPrioridadl.setGeometry(QtCore.QRect(30, 10, 61, 17))
        self.labelPrioridadl.setObjectName(_fromUtf8("labelPrioridadl"))
        self.fieldPrioridad = QtGui.QLineEdit(self.frame)
        self.fieldPrioridad.setGeometry(QtCore.QRect(30, 40, 51, 29))
        self.fieldPrioridad.setObjectName(_fromUtf8("fieldPrioridad"))
        
        ##Only Integers
        self.intValid=QtGui.QIntValidator()
        self.fieldMemoria.setValidator(self.intValid)
        self.fieldMemoriaP.setValidator(self.intValid)
        self.fieldPrioridad.setValidator(self.intValid)
        self.fieldRafaga.setValidator(self.intValid)
        self.fieldQuantum.setValidator(self.intValid)


        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Simulador de procesos", None))
        self.comboAlgoritmo.setItemText(0, _translate("MainWindow", "Round-Robin", None))
        self.comboAlgoritmo.setItemText(1, _translate("MainWindow", "Shortest Job First", None))
        self.comboAlgoritmo.setItemText(2, _translate("MainWindow", "First-Come First-Served", None))
        self.comboAlgoritmo.setItemText(3, _translate("MainWindow", "Priority Scheduling", None))
        self.labelTitulo.setText(_translate("MainWindow", "Simulador de Procesos", None))
        self.labelAlgoritmo.setText(_translate("MainWindow", "Algoritmo de Planificacion", None))
        self.labelDatos.setText(_translate("MainWindow", "Datos del proceso", None))
        self.labelNombre.setText(_translate("MainWindow", "Nombre", None))
        self.labelRafaga.setText(_translate("MainWindow", "Rafaga", None))
        item = self.TablaEstado.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nombre", None))
        item = self.TablaEstado.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Rafaga", None))
        item = self.TablaEstado.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Memoria", None))
        item = self.TablaEstado.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estado", None))
        item = self.TablaEstado.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Porcentaje %", None))
        self.btnAgregar.setText(_translate("MainWindow", "Agregar", None))
        self.btnBorrar.setText(_translate("MainWindow", "Borrar Campos", None))
        self.btnIniciar.setText(_translate("MainWindow", "Iniciar", None))
        self.btnReiniciar.setText(_translate("MainWindow", "Reiniciar", None))
        self.btnEliminar.setText(_translate("MainWindow", "Eliminar", None))
        self.labelTIempototal.setText(_translate("MainWindow", "Tiempo Total", None))
        self.btnRandom.setText(_translate("MainWindow", "Proceso Random", None))
        self.btnDetener.setText(_translate("MainWindow", "Detener", None))
        self.btnEliminartodo.setText(_translate("MainWindow", "Eliminar Todo", None))
        self.labelMemoria.setText(_translate("MainWindow", "Memoria Total", None))
        self.btnEstablecerQuantum.setText(_translate("MainWindow", "Establecer", None))
        self.labelQuantum.setText(_translate("MainWindow", "Quantum", None))
        self.labelMemoria_2.setText(_translate("MainWindow", "Memoria", None))
        self.labelPrioridadl.setText(_translate("MainWindow", "Prioridad", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

